apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-qontract-reconcile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-qontract-reconcile
    app.kubernetes.io/part-of: go-qontract-reconcile
  name: go-qontract-reconcile
spec:
  port:
    targetPort: 9090
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-qontract-reconcile
    weight: 100
status: {}
